/* ${filename}

{{IS_NOTE
	Purpose:
		
	Description:
		
	History:
	${datetime}, auto generated by ${author}
}}IS_NOTE

Copyright (C) ${year} Potix Corporation. All Rights Reserved.

{{IS_RIGHT
	This program is distributed under GPL Version 2.0 in the hope that
	it will be useful, but WITHOUT ANY WARRANTY.
}}IS_RIGHT
*/
package ${package};

import ${importclass};
import ${package}.impl.BranchTag;

/**
 * The JSP tag to represent "${class}" component in ZK's component definition.
 * @author ${author}
 *
 */
public class ${class}Tag extends BranchTag {
	/**
	 * 
	 * @return The name of the component from the ZK Component Definition: "${!class}".
	 */
	protected String getComponentName(){
		return "${!class}";
	}

}
