/* DoublespinnerTag.java

{{IS_NOTE
	Purpose:
		
	Description:
		
	History:
		2010/12/29  11:04:19 , auto generated by Ian Tsai
}}IS_NOTE

Copyright (C) 2007 Potix Corporation. All Rights Reserved.

{{IS_RIGHT
	This program is distributed under GPL Version 2.0 in the hope that
	it will be useful, but WITHOUT ANY WARRANTY.
}}IS_RIGHT
*/
package org.zkoss.jsp.zul;

import org.zkoss.zul.Doublespinner;
import org.zkoss.jsp.zul.impl.BranchTag;

/**
 * The JSP tag to represent "Doublespinner" component in ZK's component definition.
 * @author Ian Tsai
 *
 */
public class DoublespinnerTag extends BranchTag {
	/**
	 * 
	 * @return The name of the component from the ZK Component Definition: "doublespinner".
	 */
	protected String getComponentName(){
		return "doublespinner";
	}

}
