/* BandinfoTag.java

{{IS_NOTE
	Purpose:
		
	Description:
		
	History:
	2008/11/27  16:42:03 , auto generated by Flyworld
}}IS_NOTE

Copyright (C) 2008 Potix Corporation. All Rights Reserved.

{{IS_RIGHT
	This program is distributed under GPL Version 2.0 in the hope that
	it will be useful, but WITHOUT ANY WARRANTY.
}}IS_RIGHT
*/
package org.zkoss.jsp.zul;

import org.zkoss.jsp.zul.impl.BranchTag;

/**
 * The JSP tag to represent "Bandinfo" component in ZK's component definition.
 * @author Flyworld
 *
 */
public class BandinfoTag extends BranchTag {
	/**
	 * 
	 * @return The name of the component from the ZK Component Definition: "bandinfo".
	 */
	protected String getComponentName(){
		return "bandinfo";
	}

}
