/* WindowTag.java

{{IS_NOTE
	Purpose:
		
	Description:
		
	History:
	2008/11/27  16:42:03 , auto generated by Flyworld
}}IS_NOTE

Copyright (C) 2008 Potix Corporation. All Rights Reserved.

{{IS_RIGHT
	This program is distributed under GPL Version 2.0 in the hope that
	it will be useful, but WITHOUT ANY WARRANTY.
}}IS_RIGHT
*/
package org.zkoss.jsp.zul;

import org.zkoss.zul.Window;
import org.zkoss.jsp.zul.impl.BranchTag;

/**
 * The JSP tag to represent "Window" component in ZK's component definition.
 * @author Flyworld
 *
 */
public class WindowTag extends BranchTag {
	/**
	 * 
	 * @return The name of the component from the ZK Component Definition: "window".
	 */
	protected String getComponentName(){
		return "window";
	}

}
